FROM nvcr.io/nvidia/pytorch:23.09-py3

# code cli
RUN wget -c "https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64" -O - | tar -xz -C /usr/local/bin

RUN pip install transformers
